services:
  postgres:
    image: postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data:/data
    environment:
      POSTGRES_PASSWORD: "postsql"
    ports:
      - "5432:5432"